/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as PrivateStatsRouteImport } from './routes/_private/stats'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivatePaymentMethodsRouteImport } from './routes/_private/payment-methods'
import { Route as PrivateCategoriesRouteImport } from './routes/_private/categories'
import { Route as PrivateCalendarRouteImport } from './routes/_private/calendar'
import { Route as PrivateAdminRouteImport } from './routes/_private/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicAuthPathRouteImport } from './routes/_public/auth/$path'
import { Route as PrivateSettingsPathRouteImport } from './routes/_private/settings/$path'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateStatsRoute = PrivateStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePaymentMethodsRoute = PrivatePaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCategoriesRoute = PrivateCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCalendarRoute = PrivateCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminRoute = PrivateAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthPathRoute = PublicAuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateSettingsPathRoute = PrivateSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/admin': typeof PrivateAdminRoute
  '/calendar': typeof PrivateCalendarRoute
  '/categories': typeof PrivateCategoriesRoute
  '/payment-methods': typeof PrivatePaymentMethodsRoute
  '/profile': typeof PrivateProfileRoute
  '/stats': typeof PrivateStatsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stats': typeof ApiStatsRoute
  '/settings/$path': typeof PrivateSettingsPathRoute
  '/auth/$path': typeof PublicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/admin': typeof PrivateAdminRoute
  '/calendar': typeof PrivateCalendarRoute
  '/categories': typeof PrivateCategoriesRoute
  '/payment-methods': typeof PrivatePaymentMethodsRoute
  '/profile': typeof PrivateProfileRoute
  '/stats': typeof PrivateStatsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stats': typeof ApiStatsRoute
  '/settings/$path': typeof PrivateSettingsPathRoute
  '/auth/$path': typeof PublicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/admin': typeof PrivateAdminRoute
  '/_private/calendar': typeof PrivateCalendarRoute
  '/_private/categories': typeof PrivateCategoriesRoute
  '/_private/payment-methods': typeof PrivatePaymentMethodsRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/stats': typeof PrivateStatsRoute
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stats': typeof ApiStatsRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/settings/$path': typeof PrivateSettingsPathRoute
  '/_public/auth/$path': typeof PublicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/categories'
    | '/payment-methods'
    | '/profile'
    | '/stats'
    | '/api/files'
    | '/api/health'
    | '/api/stats'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/categories'
    | '/payment-methods'
    | '/profile'
    | '/stats'
    | '/api/files'
    | '/api/health'
    | '/api/stats'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/admin'
    | '/_private/calendar'
    | '/_private/categories'
    | '/_private/payment-methods'
    | '/_private/profile'
    | '/_private/stats'
    | '/api/files'
    | '/api/health'
    | '/api/stats'
    | '/_private/'
    | '/_private/settings/$path'
    | '/_public/auth/$path'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiFilesRoute: typeof ApiFilesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/stats': {
      id: '/_private/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof PrivateStatsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/payment-methods': {
      id: '/_private/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PrivatePaymentMethodsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/categories': {
      id: '/_private/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateCategoriesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/calendar': {
      id: '/_private/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof PrivateCalendarRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin': {
      id: '/_private/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/$path': {
      id: '/_public/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof PublicAuthPathRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/settings/$path': {
      id: '/_private/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof PrivateSettingsPathRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateAdminRoute: typeof PrivateAdminRoute
  PrivateCalendarRoute: typeof PrivateCalendarRoute
  PrivateCategoriesRoute: typeof PrivateCategoriesRoute
  PrivatePaymentMethodsRoute: typeof PrivatePaymentMethodsRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateStatsRoute: typeof PrivateStatsRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateSettingsPathRoute: typeof PrivateSettingsPathRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRoute: PrivateAdminRoute,
  PrivateCalendarRoute: PrivateCalendarRoute,
  PrivateCategoriesRoute: PrivateCategoriesRoute,
  PrivatePaymentMethodsRoute: PrivatePaymentMethodsRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateStatsRoute: PrivateStatsRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateSettingsPathRoute: PrivateSettingsPathRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthPathRoute: typeof PublicAuthPathRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthPathRoute: PublicAuthPathRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiFilesRoute: ApiFilesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
