/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateStatsRouteImport } from './routes/_private/stats'
import { Route as PrivateSettingsRouteImport } from './routes/_private/settings'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateCalendarRouteImport } from './routes/_private/calendar'
import { Route as PrivateAdminRouteImport } from './routes/_private/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateStatsRoute = PrivateStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateCalendarRoute = PrivateCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminRoute = PrivateAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/admin': typeof PrivateAdminRoute
  '/calendar': typeof PrivateCalendarRoute
  '/profile': typeof PrivateProfileRoute
  '/settings': typeof PrivateSettingsRoute
  '/stats': typeof PrivateStatsRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/api/files': typeof ApiFilesRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/admin': typeof PrivateAdminRoute
  '/calendar': typeof PrivateCalendarRoute
  '/profile': typeof PrivateProfileRoute
  '/settings': typeof PrivateSettingsRoute
  '/stats': typeof PrivateStatsRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/api/files': typeof ApiFilesRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/admin': typeof PrivateAdminRoute
  '/_private/calendar': typeof PrivateCalendarRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_private/stats': typeof PrivateStatsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/api/files': typeof ApiFilesRoute
  '/api/stats': typeof ApiStatsRoute
  '/_private/': typeof PrivateIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/login'
    | '/reset-password'
    | '/api/files'
    | '/api/stats'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/login'
    | '/reset-password'
    | '/api/files'
    | '/api/stats'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/admin'
    | '/_private/calendar'
    | '/_private/profile'
    | '/_private/settings'
    | '/_private/stats'
    | '/_public/login'
    | '/_public/reset-password'
    | '/api/files'
    | '/api/stats'
    | '/_private/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiFilesRoute: typeof ApiFilesRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/stats': {
      id: '/_private/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof PrivateStatsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/calendar': {
      id: '/_private/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof PrivateCalendarRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin': {
      id: '/_private/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateAdminRoute: typeof PrivateAdminRoute
  PrivateCalendarRoute: typeof PrivateCalendarRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
  PrivateStatsRoute: typeof PrivateStatsRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRoute: PrivateAdminRoute,
  PrivateCalendarRoute: PrivateCalendarRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
  PrivateStatsRoute: PrivateStatsRoute,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiFilesRoute: ApiFilesRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
